name: Sync upstream

on:
  schedule:
    - cron: '0 0 * * 0' # weekly at midnight on Sunday
  workflow_dispatch: {}

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the fork repository
        uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0
      - name: Set up git
        run: |
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ github.actor }}@users.noreply.github.com'
          git remote add upstream https://github.com/PipedreamHQ/pipedream.git
          git fetch upstream
          git merge upstream/master --strategy-option theirs
      - name: Push changes back to fork
        run: |
          git push origin master
